name: moneybook
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  data:
    path: packages/data
  flutter_animated_indicator:
    path: packages/animated_indicator

  cloud_firestore: "^0.14.1+3"
  firebase_auth:
  firebase_core:
  flutter:
    sdk: flutter
  flutter_riverpod:
  pull_to_refresh: ^1.6.2
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
